/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogowanieRouteImport } from './routes/logowanie'
import { Route as PortfelRouteImport } from './routes/portfel'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SprzedajRouteImport } from './routes/sprzedaj'
import { Route as UstawieniaRouteImport } from './routes/ustawienia'
import { Route as WiadomosciRouteImport } from './routes/wiadomosci'
import { Route as ZamowieniaRouteImport } from './routes/zamowienia'
import { Route as OfertaIdRouteImport } from './routes/oferta.$id'
import { Route as UzytkownikNameRouteImport } from './routes/uzytkownik.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogowanieRoute = LogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfelRoute = PortfelRouteImport.update({
  id: '/portfel',
  path: '/portfel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SprzedajRoute = SprzedajRouteImport.update({
  id: '/sprzedaj',
  path: '/sprzedaj',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaRoute = UstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => rootRouteImport,
} as any)
const WiadomosciRoute = WiadomosciRouteImport.update({
  id: '/wiadomosci',
  path: '/wiadomosci',
  getParentRoute: () => rootRouteImport,
} as any)
const ZamowieniaRoute = ZamowieniaRouteImport.update({
  id: '/zamowienia',
  path: '/zamowienia',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaIdRoute = OfertaIdRouteImport.update({
  id: '/oferta/$id',
  path: '/oferta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UzytkownikNameRoute = UzytkownikNameRouteImport.update({
  id: '/uzytkownik/$name',
  path: '/uzytkownik/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/portfel': typeof PortfelRoute
  '/profil': typeof ProfilRoute
  '/sprzedaj': typeof SprzedajRoute
  '/ustawienia': typeof UstawieniaRoute
  '/wiadomosci': typeof WiadomosciRoute
  '/zamowienia': typeof ZamowieniaRoute
  '/oferta/$id': typeof OfertaIdRoute
  '/uzytkownik/$name': typeof UzytkownikNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/portfel': typeof PortfelRoute
  '/profil': typeof ProfilRoute
  '/sprzedaj': typeof SprzedajRoute
  '/ustawienia': typeof UstawieniaRoute
  '/wiadomosci': typeof WiadomosciRoute
  '/zamowienia': typeof ZamowieniaRoute
  '/oferta/$id': typeof OfertaIdRoute
  '/uzytkownik/$name': typeof UzytkownikNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/portfel': typeof PortfelRoute
  '/profil': typeof ProfilRoute
  '/sprzedaj': typeof SprzedajRoute
  '/ustawienia': typeof UstawieniaRoute
  '/wiadomosci': typeof WiadomosciRoute
  '/zamowienia': typeof ZamowieniaRoute
  '/oferta/$id': typeof OfertaIdRoute
  '/uzytkownik/$name': typeof UzytkownikNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logowanie'
    | '/portfel'
    | '/profil'
    | '/sprzedaj'
    | '/ustawienia'
    | '/wiadomosci'
    | '/zamowienia'
    | '/oferta/$id'
    | '/uzytkownik/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logowanie'
    | '/portfel'
    | '/profil'
    | '/sprzedaj'
    | '/ustawienia'
    | '/wiadomosci'
    | '/zamowienia'
    | '/oferta/$id'
    | '/uzytkownik/$name'
  id:
    | '__root__'
    | '/'
    | '/logowanie'
    | '/portfel'
    | '/profil'
    | '/sprzedaj'
    | '/ustawienia'
    | '/wiadomosci'
    | '/zamowienia'
    | '/oferta/$id'
    | '/uzytkownik/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogowanieRoute: typeof LogowanieRoute
  PortfelRoute: typeof PortfelRoute
  ProfilRoute: typeof ProfilRoute
  SprzedajRoute: typeof SprzedajRoute
  UstawieniaRoute: typeof UstawieniaRoute
  WiadomosciRoute: typeof WiadomosciRoute
  ZamowieniaRoute: typeof ZamowieniaRoute
  OfertaIdRoute: typeof OfertaIdRoute
  UzytkownikNameRoute: typeof UzytkownikNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logowanie': {
      id: '/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof LogowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfel': {
      id: '/portfel'
      path: '/portfel'
      fullPath: '/portfel'
      preLoaderRoute: typeof PortfelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprzedaj': {
      id: '/sprzedaj'
      path: '/sprzedaj'
      fullPath: '/sprzedaj'
      preLoaderRoute: typeof SprzedajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia': {
      id: '/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof UstawieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiadomosci': {
      id: '/wiadomosci'
      path: '/wiadomosci'
      fullPath: '/wiadomosci'
      preLoaderRoute: typeof WiadomosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zamowienia': {
      id: '/zamowienia'
      path: '/zamowienia'
      fullPath: '/zamowienia'
      preLoaderRoute: typeof ZamowieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta/$id': {
      id: '/oferta/$id'
      path: '/oferta/$id'
      fullPath: '/oferta/$id'
      preLoaderRoute: typeof OfertaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uzytkownik/$name': {
      id: '/uzytkownik/$name'
      path: '/uzytkownik/$name'
      fullPath: '/uzytkownik/$name'
      preLoaderRoute: typeof UzytkownikNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogowanieRoute: LogowanieRoute,
  PortfelRoute: PortfelRoute,
  ProfilRoute: ProfilRoute,
  SprzedajRoute: SprzedajRoute,
  UstawieniaRoute: UstawieniaRoute,
  WiadomosciRoute: WiadomosciRoute,
  ZamowieniaRoute: ZamowieniaRoute,
  OfertaIdRoute: OfertaIdRoute,
  UzytkownikNameRoute: UzytkownikNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
