/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SprzedajRouteImport } from './routes/sprzedaj'
import { Route as WiadomosciRouteImport } from './routes/wiadomosci'
import { Route as OfertaIdRouteImport } from './routes/oferta.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SprzedajRoute = SprzedajRouteImport.update({
  id: '/sprzedaj',
  path: '/sprzedaj',
  getParentRoute: () => rootRouteImport,
} as any)
const WiadomosciRoute = WiadomosciRouteImport.update({
  id: '/wiadomosci',
  path: '/wiadomosci',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaIdRoute = OfertaIdRouteImport.update({
  id: '/oferta/$id',
  path: '/oferta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sprzedaj': typeof SprzedajRoute
  '/wiadomosci': typeof WiadomosciRoute
  '/oferta/$id': typeof OfertaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sprzedaj': typeof SprzedajRoute
  '/wiadomosci': typeof WiadomosciRoute
  '/oferta/$id': typeof OfertaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sprzedaj': typeof SprzedajRoute
  '/wiadomosci': typeof WiadomosciRoute
  '/oferta/$id': typeof OfertaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sprzedaj' | '/wiadomosci' | '/oferta/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sprzedaj' | '/wiadomosci' | '/oferta/$id'
  id: '__root__' | '/' | '/sprzedaj' | '/wiadomosci' | '/oferta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SprzedajRoute: typeof SprzedajRoute
  WiadomosciRoute: typeof WiadomosciRoute
  OfertaIdRoute: typeof OfertaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprzedaj': {
      id: '/sprzedaj'
      path: '/sprzedaj'
      fullPath: '/sprzedaj'
      preLoaderRoute: typeof SprzedajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiadomosci': {
      id: '/wiadomosci'
      path: '/wiadomosci'
      fullPath: '/wiadomosci'
      preLoaderRoute: typeof WiadomosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta/$id': {
      id: '/oferta/$id'
      path: '/oferta/$id'
      fullPath: '/oferta/$id'
      preLoaderRoute: typeof OfertaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SprzedajRoute: SprzedajRoute,
  WiadomosciRoute: WiadomosciRoute,
  OfertaIdRoute: OfertaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
