/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfelRouteImport } from './routes/portfel'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SprzedajRouteImport } from './routes/sprzedaj'
import { Route as WiadomosciRouteImport } from './routes/wiadomosci'
import { Route as ZamowieniaRouteImport } from './routes/zamowienia'
import { Route as OfertaIdRouteImport } from './routes/oferta.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfelRoute = PortfelRouteImport.update({
  id: '/portfel',
  path: '/portfel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SprzedajRoute = SprzedajRouteImport.update({
  id: '/sprzedaj',
  path: '/sprzedaj',
  getParentRoute: () => rootRouteImport,
} as any)
const WiadomosciRoute = WiadomosciRouteImport.update({
  id: '/wiadomosci',
  path: '/wiadomosci',
  getParentRoute: () => rootRouteImport,
} as any)
const ZamowieniaRoute = ZamowieniaRouteImport.update({
  id: '/zamowienia',
  path: '/zamowienia',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaIdRoute = OfertaIdRouteImport.update({
  id: '/oferta/$id',
  path: '/oferta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfel': typeof PortfelRoute
  '/profil': typeof ProfilRoute
  '/sprzedaj': typeof SprzedajRoute
  '/wiadomosci': typeof WiadomosciRoute
  '/zamowienia': typeof ZamowieniaRoute
  '/oferta/$id': typeof OfertaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfel': typeof PortfelRoute
  '/profil': typeof ProfilRoute
  '/sprzedaj': typeof SprzedajRoute
  '/wiadomosci': typeof WiadomosciRoute
  '/zamowienia': typeof ZamowieniaRoute
  '/oferta/$id': typeof OfertaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portfel': typeof PortfelRoute
  '/profil': typeof ProfilRoute
  '/sprzedaj': typeof SprzedajRoute
  '/wiadomosci': typeof WiadomosciRoute
  '/zamowienia': typeof ZamowieniaRoute
  '/oferta/$id': typeof OfertaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portfel'
    | '/profil'
    | '/sprzedaj'
    | '/wiadomosci'
    | '/zamowienia'
    | '/oferta/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portfel'
    | '/profil'
    | '/sprzedaj'
    | '/wiadomosci'
    | '/zamowienia'
    | '/oferta/$id'
  id:
    | '__root__'
    | '/'
    | '/portfel'
    | '/profil'
    | '/sprzedaj'
    | '/wiadomosci'
    | '/zamowienia'
    | '/oferta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortfelRoute: typeof PortfelRoute
  ProfilRoute: typeof ProfilRoute
  SprzedajRoute: typeof SprzedajRoute
  WiadomosciRoute: typeof WiadomosciRoute
  ZamowieniaRoute: typeof ZamowieniaRoute
  OfertaIdRoute: typeof OfertaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfel': {
      id: '/portfel'
      path: '/portfel'
      fullPath: '/portfel'
      preLoaderRoute: typeof PortfelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprzedaj': {
      id: '/sprzedaj'
      path: '/sprzedaj'
      fullPath: '/sprzedaj'
      preLoaderRoute: typeof SprzedajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiadomosci': {
      id: '/wiadomosci'
      path: '/wiadomosci'
      fullPath: '/wiadomosci'
      preLoaderRoute: typeof WiadomosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zamowienia': {
      id: '/zamowienia'
      path: '/zamowienia'
      fullPath: '/zamowienia'
      preLoaderRoute: typeof ZamowieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta/$id': {
      id: '/oferta/$id'
      path: '/oferta/$id'
      fullPath: '/oferta/$id'
      preLoaderRoute: typeof OfertaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortfelRoute: PortfelRoute,
  ProfilRoute: ProfilRoute,
  SprzedajRoute: SprzedajRoute,
  WiadomosciRoute: WiadomosciRoute,
  ZamowieniaRoute: ZamowieniaRoute,
  OfertaIdRoute: OfertaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
